### ISSUE TITLE
Default docs background color

### ISSUE THREAD

**Issue by adamgayoso** [scverse/cookiecutter-scverse#112]
Is anyone opposed to an Tufte style color background? The white is very stark!

https://www.edwardtufte.com/tufte/

**Comment by grst** [comment]
won't pngs with white packground (e.g. in tutorials) look ugly?

**Comment by flying-sheep** [comment]
we shouldn’t have gone away from furo before whatever theme we use now has a dark mode.

**Comment by flying-sheep** [comment]
> Customization is also not really condoned by the furo author.

That’s simply not true: https://pradyunsg.me/furo/customisation/colors/#using-your-own-colors

**Comment by adamgayoso** [comment]
> That’s simply not true: https://pradyunsg.me/furo/customisation/colors/#using-your-own-colors

https://pradyunsg.me/furo/customisation/injecting/

**Comment by flying-sheep** [comment]
That info box just describes what every theme does:

- they *might* offer some blessed extension mechanism like CSS variables 
- they change things around, modify their CSS and HTML, and if you rely on structure staying the same, your stuff can get broken.

That’s exactly why sphinx-book-theme pins a version of the pydata theme and struggles to update to the new version: because sphinx themes are usually not designed to be extensible.

The same problem existed with GNOME: They switched the whole desktop to be CSS styled and basically told users ”theming your desktop is no longer supported starting now”

The only hope is IMHO to use a popular theme that extensions care enough about to stay compatible with.

**Comment by adamgayoso** [comment]
> That’s exactly why sphinx-book-theme pins a version of the pydata theme and struggles to update to the new version: because sphinx themes are usually not designed to be extensible.

Would be a great contribution to have you update that theme to use dark mode!

**Comment by adamgayoso** [comment]
Closing this as sphinx book theme with dark mode is now being used
