### ISSUE TITLE
Documentation for bump2version

### ISSUE THREAD

**Issue by ivirshup** [scverse/cookiecutter-scverse#51]
Right now there is no documentation on this repo for how to use bump2version. I'm a little unsure how to use it myself and had some trouble with it. 

Could this get docs? 

@ilia-kats, @Zethson

**Comment by ivirshup** [comment]
Would hatch supersede this?

**Comment by grst** [comment]
It is possible to do this with hatch, although the version would need to go to `__init__.py` instead of `pyproject.toml`: 

```
__version__ = "0.0.1"
```

```console
(default) sturm@hochvogel project-name [main] % hatch version "0.1.0"
Old: 0.0.1
New: 0.1.0
```

(see also https://hatch.pypa.io/latest/version/)

If we prefer having the version minted into `pyproject.toml` we have to stick with another version bumper. 

Note that `hatch` is the CLI while `hatchling` is the build backend. The build backend works well without the CLI. 

---

ping @flying-sheep what would you recommend?

**Comment by grst** [comment]
I think I prefer having the version in `pyproject.toml` directly, as everything is in one place. I would add in the developer docs how to setup vcs-based versioning as an alternative.
