### ISSUE TITLE
Furo theme special CSS (from scvi-tools)

### ISSUE THREAD

**Issue by ivirshup** [scverse/cookiecutter-scverse#74]
It would be good to add some of the special CSS from scvi-tools

**Comment by adamgayoso** [comment]
This is the most critical for sizing the items in the left sidebar:

https://github.com/scverse/scvi-tools/blob/c6b2b12acc14017c98bf0c3f11c822cf91cf7401/docs/_static/css/override.css#L74-L80

I like this one which makes PARAMETERS -> Parameters

https://github.com/scverse/scvi-tools/blob/c6b2b12acc14017c98bf0c3f11c822cf91cf7401/docs/_static/css/override.css#L23-L27

This one alters "Examples" and Notes sections in class inits so that it matches the parameters change

https://github.com/scverse/scvi-tools/blob/c6b2b12acc14017c98bf0c3f11c822cf91cf7401/docs/_static/css/override.css#L29-L34

This stuff is for nbsphinx outputted notebooks specifically, and I like all the changes:

https://github.com/scverse/scvi-tools/blob/c6b2b12acc14017c98bf0c3f11c822cf91cf7401/docs/_static/css/override.css#L39-L71

**Comment by flying-sheep** [comment]
> This is the most critical for sizing the items in the left sidebar:

yeah, let’s use `calc()` instead of those magic percentage numbers.
